DROP TABLE "ORDER" CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS; 
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ORDERS_ITEM CASCADE CONSTRAINTS; 
DROP SEQUENCE ORDER_SEQ;
DROP SEQUENCE ORDER_ITEM_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE ORDERS_ITEM_SEQ;
